### ISSUE TITLE
Issue with mystical agriculture seeds when bonus seeds are turned off

### ISSUE THREAD

**Issue by ZilvynraeS** [Darkhax-Minecraft/BotanyPots#116]
Good evening, I’m not sure which mod this is an issue for, but I am thinking this one is more likely so I started here. I have botany pots and mystical agriculture. For mystical agriculture I have second seeds turned off (so you need to craft each seed and not just 1 and let them multiply). It works fine when planting the crops normally, but when put in a botany pot you will still get more seeds.

**Comment by ZilvynraeS** [comment]
Realized I should probably add that I'm in MC 1.16.4, playing with Botany Pots 6.0.7, and mystical agriculture 4.1.3. I'm also playing on a custom modpack on a multiplayer server if that is relevant.

**Comment by ghost** [comment]
This can be fixed in the meantime by removing the chance for an extra seed in the json files [here](https://github.com/Darkhax-Minecraft/BotanyPots/tree/46fcd51669b51b72fe1f0914ab80672e04c2dcde/src/main/resources/data/mysticalagriculture/recipes/crops).

You might be able to override them with no extra mods following [this](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information#crops), or you could override them with the help of something like [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs).

**Comment by Darkhax** [comment]
This mod uses a different data set from the base mod, so simply turning off a config option in their mod will not affect our data set. There is currently no way to do this automatically so you will need something like a CraftTweaker script to do this.
