### ISSUE TITLE
[Request] Support for Uberous Soil from Twilight Forest.

### ISSUE THREAD

**Issue by seanimusprime** [Darkhax-Minecraft/BotanyPots#189]
Having support for the Uberous Soil from Twilight Forest would be great. Basically this soil will instantly cause anything planted on it to be fully grown. I'd try to do a datapack for it, but I have no idea what to do.

**Comment by amouranthtoo** [comment]
`{
  "type": "botanypots:soil",
  "input": {
    "item": "twilightforest:uberous_soil;"
  },
  "display": {
    "block": "twilightforest:uberous_soil"
  },
  "categories": ["dirt"],
  "ticks": 1
}
`

**Comment by amouranthtoo** [comment]
try that

**Comment by ngoetti** [comment]
According to this [Wiki](http://benimatic.com/tfwiki/index.php?title=Uberous_Soil) Uberous Soil gets transformed into regular dirt or farmland after one use. Which begs the questing if @Darkhax wants to support this kind of behavior at all, because it would not be a simple addition but require some adjusting of the mod logic.

**Comment by Darkhax** [comment]
I would be fine with this being implemented with different logic, for example making it grow 30% faster than normal. The Twilight Forest devs have expressed interest in adding support themselves however so I will leave this to them.
