### ISSUE TITLE
problem with the growth time

### ISSUE THREAD

**Issue by laboriens** [Darkhax-Minecraft/BotanyPots#207]
I am on forge 1.16.5 latest version
the botany pot latest version

since an update (reminds me more which one) the cultures (mods and vanilla) arrive at 100% with a time at 0, but get stuck for a long time as if the culture was not finished yet

**Comment by Phantom914** [comment]
Yeah I've been having issues with growth time too. I had to make my custom ones .99 to get around that. But I have a few different mulches and it goes -0.25 0.00 0.25 0.50 0.75 and .99. It doesn't seem like the times really matter because they get stuck at 100% all the time, even with vanilla chests. It only seems like it matters over a huge period of time because I have it running on a test island while I'm testing my pack.

**Comment by Darkhax** [comment]
Having a growth time of 0 is not supported. If you want "instant" crops try a tick time of 1.
