### ISSUE TITLE
Hopper Pots Not Properly Voiding

### ISSUE THREAD

**Issue by blessthebest7** [Darkhax-Minecraft/BotanyPots#209]
Forge 36.2.20
BotanyPots 7.1.30

When placed on top of a 1x1 Storage Drawer (which only stores 1 item), the hopper pot no longer voids the _fertilized essence_ drop from **Mystical Agriculture**. This causes the hopper to keep the plant at 100% until it is broken and replanted, until another _fertilized essence_ drops. It appears that the seed drops do not also cause this issue, only the _fertilized essence_ but I will update this if that changes. 
Edit: The seeds DO cause the same issue, just had it occur as I was writing the post lol

**Comment by Graywaren** [comment]
Also having this problem, or related at least. I could have sworn that if you had a plant with multiple drops and put it on a storage drawer that it would go until the whole drawer was filled, voiding the most frequent drops once they were full until the entire drawer was filled. For example, an oak tree would continue growing on a 2x2 storage drawer until the apple section was full even if the logs, leaves, and saplings were already full. Now any time it rolls an item it cannot place into a drawer it waits at 100% until it can drop that item either because of removing some of the full item or putting another inventory under it. This seems to happen with any plant.

I'm not sure if this points towards the issue being with Storage Drawers itself? Or maybe that they changed something that made the botany pot code for it no longer work. SD did put out a recent update. However, I'm not even sure that I was correct about how they worked? Since I previously put a lot of stack upgrades in drawers and perhaps I just didn't notice that they stopped when the most frequent drop was full? It became really obvious when I used a downgrade though. With any confirmation that it is actually supposed to go until the last section is full I could try to do some testing to see if it's the most recent update with SD etc. I'm currently playing Seaopolis 14 (1.16.5) and feel like I noticed this happen from Seaopolis 13 to 14 upgrade, which might further point to the SD update playing a part.

**Comment by Graywaren** [comment]
Just noticed there's another thread for this as well, linking here in case it's useful: https://github.com/Darkhax-Minecraft/BotanyPots/issues/174

*edit: my previous comment about factories and mystic ag proved untrue as they eventually got stuck and it seems server restarts will reset the growth as mentioned in the above issue*

**Comment by Darkhax** [comment]
Thanks for reporting this. I am closing this issue as discussion should be moved to #174
