### ISSUE TITLE
Enigmatica6 botany pots not working with Mystical Agriculture

### ISSUE THREAD

**Issue by TerrorInc** [Darkhax-Minecraft/BotanyPots#217]
As the title suggests I cannot put any sort of mystical farmland into the pots, nor the seeds, I am the server owner so I can modify any file needed to make this work, can someone please help :)

**Comment by Darkhax** [comment]
I believe this behavior has been specifically disabled by the Enigmatica6 pack developers for balancing reasons. You should refer to their support for more information. If that turns out not to be the case you can learn more about how crops and soils are defined in the [wiki](https://github.com/Darkhax-Minecraft/BotanyPots/wiki).
