### ISSUE TITLE
Enhancement/ATM8/Botany Pots

### ISSUE THREAD

**Issue by IsaiahMM** [Darkhax-Minecraft/BotanyPots#259]
I remember on maybe ATM 6 To The Sky or ATM7 I was able to right click, or shift right click the soil and seed into the botany pots. It would be nice to be able to do that again as when you set up a giant pot farm it can get tedious to do it by hand.

**Comment by Darkhax** [comment]
Hello, thanks for the request. Unfortunately I intentionally replaced this feature with the GUI because the old system was way too unreliable and unrealistic to improve. The crux of the issue is that items and blocks can define their own logic for when they are used to right click blocks. This can create issues such as shields in the offhand slot preventing the player from interacting with the pot, modded spells/guns/weapons unintentionally activating, and some seeds/soils being placed next to the pot instead of inside the pot. The GUI is a bit slower but much more user friendly and has less edge cases.
