### ISSUE TITLE
Suggestion: Show growable plants (or trees) and soils in JEI

### ISSUE THREAD

**Issue by Raidobw2** [Darkhax-Minecraft/BotanyPots#272]
Hi, I have a suggestion for the mod. It appears when pressing 'u' on a Botany Pot in JEI, no plants or soils are shown.

![image](https://user-images.githubusercontent.com/17010632/199653843-f08cc679-4ceb-449e-bd70-a01acbaa6333.png)

I could suggest a list of soils similar to what https://github.com/Darkhax-Minecraft/BotanyPots/issues/164 has suggested, or showing both the soils and plants in the recipes.

For example, if I pressed 'u' on a poppy, I could see the poppy and the multiple soils like so:

![image](https://user-images.githubusercontent.com/17010632/199654554-c00e08c6-d36f-4b28-8d8e-3cf68645c618.png)

Or if I pressed 'u' on grass, I could see the grass and all the plants rotating like so:

![sample_botany_pot_recipe](https://user-images.githubusercontent.com/17010632/199655325-9883fc6c-184b-4aac-9b8d-fe4af2915bd6.gif)

Potentially more information could be added, if you judge some to be helpful, like growth time, etc.

#### Why this suggestion?

It was reported to us at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1556 that it would be nice to see more information in JEI/REI. This would help players to know more easily how the botany pots can be used, and thus get into the mod when viewing available recipes with plants and such (e.g. the botany trees addon as well).

Thanks for reading!

**Comment by Darkhax** [comment]
Hello, this was already a feature on 1.16.5 but it was removed in the 1.18.2 port because both mods changed and the old support was completely broken. A new 1.18.2 update went out recently that re-adds JEI support that allows you to see which crops grow on a soil, what soils a seed grows on, and which crops output a given crop drop.

There are still some QOL features I need to add and 1.19.2 support, but this is more or less implemented. 

Edit: Here is what is currently missing.
- Pots are not registered as catalysts. This is what lets you view all recipes of a given type, like clicking on a furnace to see all smelting recipes.
- Soil modifiers are not shown in a list as #164 requests.
- Fertilizer info is not displayed at all.
- Pot interactions like right clicking dirt with a hoe are not displayed.

**Comment by Raidobw2** [comment]
Thank you for explaining 🙂 I see that the JEI support is back in the 1.18.2 update you mentioned, that's awesome!

I'm looking forward to see those additional QoL features be added in at some point 😄 cheers and good luck with the future development of your mod!

**Comment by AnAwesomGuy** [comment]
There doesn't seem to be REI support.
At least not in 1.18.2 Fabric.
