### ISSUE TITLE
1.18.2 Hemp 

### ISSUE THREAD

**Issue by Sunekaer** [Darkhax-Minecraft/BotanyPots#273]
I added https://github.com/Darkhax-Minecraft/BotanyPots/commit/292f47791735c0ebcab1e265f53ea76b4743c84c as data pack to 1.18.2 ( [https://pste.me/@/swfTUlQ4u0g](https://pste.me/@/swfTUlQ4u0g) ) 
The plant grows up ones and does one drop and the just gets stuck fully grown

**Comment by Darkhax** [comment]
Are  you sure that's the right file? There are several issues with that file that would prevent it from loading.

**Comment by Sunekaer** [comment]
If you see my paste, i have adjusted it to the 1.18 version.
it loads, the plant grows, it does drop items, it just never breaks and restart the growth

**Comment by Darkhax** [comment]
Okay, this issue should be fixed in the latest update. There were a few different issues here.

1) When a crop is harvested but yields no drops it will confuse the auto-harvest logic. It would basically act like the inventory was full because no items were moved. This has now been fixed so all your crops should work like normal.

2) The hemp crop on 1.19.2 was user submitted and has some quality issues. For some reason they used the 1.16.5 format and not the 1.18.2+ format. It also has a growth time and drop list that is not in line with the balancing of the mod in 1.18.2+. The new update includes a proper version of hemp for 1.18.2 and I will update the 1.19.2 file soon.

**Comment by Sunekaer** [comment]
Thanks Darkhax
