### ISSUE TITLE
Problem with Tube coral and Tube coral block in hopper pots

### ISSUE THREAD

**Issue by atealein** [Darkhax-Minecraft/BotanyPots#293]
Hi, I'm playing on Vault Hunters modpack, where Botany Pots is used (version Forge-1.18.2-8.0.12). I've recently set up all the different corals, blocks and fans to grow and I noticed two of them are bugged (I've asked other people playing the modpack to confirm this and they also see this problem). In short - if you place Tube coral and Tube coral block in a hopper pot, they grow for few cycles (1-6, a bit random) but then stop at the highest moment - they don't output harvest even in their inner inventory, the animations are also stuck with the block at the largest possible size. 

I've reported this issue to the VH as well, but I am not sure if it originates in the Botany Pots mod itself maybe you should be aware too.

**Comment by Darkhax** [comment]
Hello,

This is a known bug that occurs when a pot completes a harvest cycle but does not produce any drops to harvest. This can happen when a crop doesn't have at least one guaranteed drop. Fortunately this bug was fixed in [8.0.16](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/4070038) which was released several months ago. I would recommend updating to [8.0.23](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/4183256) though. It has a few additional bug fixes and other improvements. You should also advise VH that they are using an outdated version of the mod and should update it soon.
