### ISSUE TITLE
request 1.18 config to disable GrowthAnimation or disable render

### ISSUE THREAD

**Issue by nightmare3007** [Darkhax-Minecraft/BotanyPots#310]
can we return the config file for the mod like 1.16.5 to the 1.18 or 1.19:
----------------------------------------
#Whether or not the growth animation should be played.
	useGrowthAnimation = true
	#Whether or not the soil in pots should be rendered.
	renderSoil = true
	#Whether or not crops should render in pots.
	renderCrop = true
	#Whether or not break effects should occur when harvested.
	breakEffects = true
	#The render distance of a botany pot.
	#Range: 1.0 ~ 4096.0
	renderDistance = 64.0
--------------------------------------------
need to make it to reduce lag.
notes : 
i dont understand why render {Growth Animation - break effects} on hopper type as there are not needed.
1- render soil and final stage of Growth Animation {fully mature crop} if Botany Pots run (work) with no problem {if hop type has space or chest still has space}.
2- if Botany Pots stop running render soil only (or render lava) to indicate that Botany Pots is full or storage system is full.
3-use Growth Animation for non hopper type.

**Comment by Darkhax** [comment]
Hello, I am not planning to re-add these options as they make the mod worse without giving anything of substantial value.

> useGrowthAnimation = true

This animation has 0 impact on FPS. The animation simply changes the size of the model and having larger/smaller models doesn't impact render times because the polygon count is not changing. This option was originally added to prove this point and I feel it has sufficiently done that.

> renderSoil = true
renderCrop = true

While these options do improve performance it is only a marginal improvement. A pot with both rendering uses less rendering resources than a static vanilla sign. 

> breakEffects = true

Break effects were removed in the 1.18.2 update. No need to re-add an option to disable them if they don't exist.

> renderDistance = 64.0

The default option was was reduced to 32. Any lower than this makes for a bad user experience.

Here are some tips to improve performance.

1) Make sure you're using the latest version of the mod. There have been several bug fixes and optimizations.
2) Avoid vanilla hoppers and poorly performing inventory blocks. Item transfer logistics use significantly more system resources than rendering. 
3) Spread out your build so pots are not constantly within render distance.
