### ISSUE TITLE
In newest version there are no diamond seeds dropping

### ISSUE THREAD

**Issue by flibz** [Darkhax-Minecraft/BotanyPots#311]
This is in regards to Mystical Agriculture.

Is this changed on purpose or is it a bug? I did not see anything in the changelog about it, thanks in advance. 

Love your mod, thanks for everything you are doing!

**Comment by Darkhax** [comment]
Hello, looking at the relevant code diamond seeds have a 1% chance to drop each harvest. Is it possible that you have just been unlucky with the drops?

**Comment by flibz** [comment]
> Hello, looking at the relevant code diamond seeds have a 1% chance to drop each harvest. Is it possible that you have just been unlucky with the drops?

Hey, I even checked the recipe, and the seed is gone there. In the last version it is there.

**Comment by Darkhax** [comment]
Which version are you using?

**Comment by flibz** [comment]
Hey, sorry about that, I am on 1.19.2 9.0.28, but thing is I also tried changing it back to 9.0.27 that works on ATM8 1.0.13, and it is still not there. Soooo there might be another mod that is interfering here?

I am adding a screenshot so you can see it is missing though.

 ![Crops](https://user-images.githubusercontent.com/49027307/228917924-e4757f5b-408b-4f49-8f36-2db96902de9f.JPG)

**Comment by Darkhax** [comment]
I've checked the file for that version and the seed is definitely there, it also shows up in game. With the way this mod works any issues with a drop would cause the whole recipe not to work so changes like this are often intentional. For example it looks like All The Mods has a script to remove these drops. https://github.com/AllTheMods/ATM-8/blob/dd18ed8b7134e1749efb9e468bdf4c3e3c2d92fb/kubejs/server_scripts/mods/mysticalagriculture/crops.js#L60-L84
