### ISSUE TITLE
Hopper botany pots bypassing side check

### ISSUE THREAD

**Issue by tplc10** [Darkhax-Minecraft/BotanyPots#321]
Hopper botany pots are bypassing allowed I/O sides and inputting into every slot possible on the inventory of the block below them, even the output slot. 

Likely due to the bit of code [here](https://github.com/Darkhax-Minecraft/BotanyPots/blob/e148bf251e63e39fce1a91eac5e84172b0d83022/Common/src/main/java/net/darkhax/botanypots/block/BlockEntityBotanyPot.java#LL162C8-L162C8) where the forceInsert parameter is set to true.

**Comment by Darkhax** [comment]
Hello, thanks for looking into this and reporting the issue. Your assessment of the code there is not correct. While the forceInsert parameter does allow ignoring sided inventory rules the inventory being accessed in that code snippet is the botany pots own internal inventory. This code is required to modify the output only slots of the botany pot. 

The relevant code to your issue would be the [attemptExport](https://github.com/Darkhax-Minecraft/BotanyPots/blob/e148bf251e63e39fce1a91eac5e84172b0d83022/Common/src/main/java/net/darkhax/botanypots/block/BlockEntityBotanyPot.java#L178-L204) code which does test for the relevant side and will not force the input. I am guessing the issue you are experiencing is related to the block itself not accurately accounting for sides as the hopper pots work fine with furnaces. For example a hopper pot with wheat seeds will only import into the top slot of the hopper, any additional drops like seeds stay in the hopper pot rather than going into the furnace.
