### ISSUE TITLE
Click machine only working on 2 sides of a botany pot

### ISSUE THREAD

**Issue by DarkShadow012** [Darkhax-Minecraft/BotanyPots#337]
Why is only working on west and south and not on the other two?

**Comment by Darkhax** [comment]
Hello, I am able to recreate this issue however for me it's when the click machine is facing West and North that it doesn't work. Can you double check that you have the right direction? Using f3 and checking the blockstate properties on the right for the facing property would be the most consistent way to verify this. 

Edit: Also linking to https://github.com/Shadows-of-Fire/ClickMachine/issues/51 to link the two issues.

**Comment by DarkShadow012** [comment]
I made a video for you to see because im bad at explanations:
https://imgur.com/a/2BYuvbr

**Comment by Darkhax** [comment]
After talking with the dev of ClickMachine a bit I think the issue is with their mod. There are some funky behaviours with how the click machine tries to click on blocks, for example vanilla doors and trap doors are also not clicked when positioned in certain ways. Please use the issue on their repo for further updates.

![image2](https://github.com/Darkhax-Minecraft/BotanyPots/assets/2250798/891c4e17-1d55-4f31-9094-83517a905722)
![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/2250798/955c65d0-0423-4424-8a4c-c740d5bb5dd7)
