### ISSUE TITLE
1.20.1 - Cant Place Pot

### ISSUE THREAD

**Issue by Milstilteinn** [Darkhax-Minecraft/BotanyPots#349]
Hi Team,

MC Version 1.20.1 can place botany pots solo world, loaded mod on to MineOS Server, tested using only pot mod, Cant place pot instantly Vanishes, was using latest required files, am a little confused, any assistance would be appreciated, (PS am running fabric latest server files)

Kind Regards,

Mills

**Comment by Darkhax** [comment]
Hello, 

Modded blocks instantly vanishing on a dedicated server is usually caused by the server not having the mod installed. You can verify this by looking at the latest server.log file. If you're installing the mod on Fabric make sure you are using the Fabric JAR and not the Forge JAR as Fabric can not load Forge files.

**Comment by Milstilteinn** [comment]
HI Team,

Appreciated the fast reply, did some checking in the logfile and i was launching the wrong server jar, appreciate the help, sorry for the silly question,

Kind Regards,

Mils
