### ISSUE TITLE
[bug] for Uberous Soil from Twilight Forest 

### ISSUE THREAD

**Issue by Nanovoin** [Darkhax-Minecraft/BotanyPots#352]
twilightforest-1.19.2-4.2.1518-universal.jar
on BotanyPots-Forge-1.19.2-9.0.39.jar Uberous Soil not working
on BotanyPots-Forge-1.19.2-9.0.38.jar Uberous Soil not working
on BotanyPots-Forge-1.19.2-9.0.33.jar Uberous Soil is working

Why?

**Comment by Darkhax** [comment]
Botany Pots did not have Twilight Forest support in 9.0.33, it was only added in 9.0.36. It's possible you have a 3rd party mod or script that was adding support and it broke when we added official support. I noticed the official version can only grow sand crops though, which is now fixed in 9.0.40.
