### ISSUE TITLE
Add support for additional Mystical Agriculture seeds

### ISSUE THREAD

**Issue by lethalitycomplex** [Darkhax-Minecraft/BotanyPots#359]
I had a look through the list of seeds that can be grown in botany pots from Mystical Agriculture, and saw that both Soulium seeds from the base mod, and the Flux-Infused Ingot/Flux-Infused Gem seeds are missing recipes. 

I wanted to put an issue here for posterity's sake, but I'd be glad to put together a PR with the required recipes.

**Comment by Darkhax** [comment]
Thanks for letting me know about this. Which version of the game and mods are you using?

**Comment by SonyStinks** [comment]
I can't speak for the other guy, but I noticed this exact problem in your version for 1.20.1. There are 180+ mods active on my game, but the only relevant ones are Mystical Agriculture, Mystical Agradditions, and Redstone Arsenal.  

For thoroughness' sake, I made a new instance of 1.20.1 with just MA+Agradditions+Cucumber library, EnderIO (to test Soularium), and CoFH's Thermal/Redstone Arsenal mods/libraries. The issue is missing recipes, and sure enough it still exists: I can grow MA's EnterIO-compatible "Soularium" just fine, but not the main mod's "Soulium" or the Thermal-compatible Flux-Infused seeds.  The seeds just won't go into the pot.

**Comment by lethalitycomplex** [comment]
> Thanks for letting me know about this. Which version of the game and mods are you using?

Same boat as @SonyStinks, 1.20.1 game version, and a long list of mods (playing the Fantasy Skies modpack), the only ones of import being Mystical Agriculture, Mystical Agradditions and Redstone Arsenal. I also noticed it by looking through the source for the MA recipes, and not seeing the recipes there, but there were some for every other material I checked (both core materials and modded ones, e.g Thermal alloys, EnderIO alloys).

**Comment by Darkhax** [comment]
A new update should be on CurseForge soon that adds support for these crops. Please try it out and let me know if it resolves your issue. [13.0.19](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5029670). CurseForge is still processing the file so the link won't work for a few minutes.
