### ISSUE TITLE
Proof that the growning animation does actually effect the fps

### ISSUE THREAD

**Issue by oliverrook** [Darkhax-Minecraft/BotanyPots#37]
I saw an issue earlier about disabling the growth animation, and it was stated that it doesn't effect the fps. Well, I placed about 600 pots, and it cuts my fps in half.
This is on a flatworld as well, so there's nothing else that could be effecting the fps.
Video showing this:
https://www.youtube.com/watch?v=wW0qsgsq9Yc

**Comment by Darkhax** [comment]
Hello, 

You've misunderstood my comment on that issue. It is not the growing animation which causes the lag, it is the rendering of the soil and the crop itself. If you disable the animation but continue to render the contents of the pot it will be virtually identical in terms of FPS impact. 

The botany pots are extremely efficient with their rendering compared to other tile entities. In the other thread I did a comparison for 400 botany pots with growth animations compared to 400 signs with a few words on them. The botany pots were slightly more efficient than the signs.

After that issue was closed I decided to look into ways which the rendering could be improved further. I found a few experimental changes which can reduce rendering times up to 35% for the pots. This change was pushed to Curse Forge as V2.0.17. 

It is undeniable that large quantities of botany pots will affect your FPS even with the experimental improvements, however this is the case with any tile entity in Minecraft.
