### ISSUE TITLE
[QUESTION] <Can't get the datapack to work>

### ISSUE THREAD

**Issue by Silverfrost9** [Darkhax-Minecraft/BotanyPots#375]
### Question

I'm trying to make a datapacks that allows me to put cultural delights and byg stuff into the botany pots. The blueberries worked without the datapack but the rest of the berries don't work and some of the byg flowers work and others don't. I tried to make a datapack to add these in but it doesn't seem to be working. Here's my datapack. I am on minecraft 1.16.5 and forge version 36.2.41
[silversbotany.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/14441552/silversbotany.zip)

**Comment by Silverfrost9** [comment]
Oh I managed to get nightshade berries to work but not crimson berries. I also got the cultural delights crops to work but i can only plant the rice in dirt when it's supposed to be grown in water

(edit i figured out that crimson berries grows on overgrown netherrack but it's not supposed to)
[silversbotany2.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/14441761/silversbotany2.zip)

**Comment by Silverfrost9** [comment]
Last addition, the cucumber, corn, and eggplant won't harvest into a chest when placed into a botany hopper pot. It says the growth is 100% without reaching mature crop and then just doesn't harvest. Even when placed into a normal botany pot

**Comment by Darkhax** [comment]
Hello, the issues you've mentioned here are all explained in the log file. It looks like you were using the 1.20.4 documentation for 1.16.5 but that will not work. You should reference [this](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information/72de43ae43b04a3c00be233bf3979f534db61eae) documentation instead, and cross reference it with the [examples](https://github.com/Darkhax-Minecraft/BotanyPots/tree/1.16.5/src/main/resources/data) included with the mod.

Looking specifically at the cucumber crop, the following warning is printed in the log when using your datapack. `[Server thread/WARN]: The crop culturaldelights:crops/cucumber has no results array. This means it won't drop anything!`. This is because you used `drops` for the property key but that version of the game used `results`.

**Comment by Silverfrost9** [comment]
Okay, I did as instructed and it does work better but I'm still struggling with it. I copied the code from the kelp file for the rice for it to be planted in water but it still won't be planted in there. The eggplants wont drop seeds and them and the cucumber keep registering as broken textures. The corn kernels won't plant at all ;-;

![welp](https://github.com/Darkhax-Minecraft/BotanyPots/assets/161662778/0d0fd4f0-f56b-4da0-9855-298249096df4)
[silversbotany3.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/14471428/silversbotany3.zip)

**Comment by Silverfrost9** [comment]
Okay, I got it to work somewhat? There's still issues with the rice but the others seemed to fix themselves mostly? I'm still working on intergrating Farmers Respite with the teas but I'm still struggling with getting the seeds to drop from cultural delights and the water issue for rice The textures are unbroken though which is something.
[silversbotany4.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/14471547/silversbotany4.zip)

**Comment by Darkhax** [comment]
Your changes to rice is not working because the authors of Farmers Delight added the rice recipe themselves. You will need to put the file in the same location as theirs to override it. `data/farmersdelight/recipes/integration/botanypots/crops/rice_crop.json`.

**Comment by Darkhax** [comment]
I am going to close this issue for now. You're already on the Discord and I feel that's a better place to handle tech support like this. I've given you the role to post files in your thread there so you can upload zips/jsons/pngs easier.
