### ISSUE TITLE
[BUG] Time in a bottle does not effect Botany Pots

### ISSUE THREAD

**Issue by milkev** [Darkhax-Minecraft/BotanyPots#385]
### Minecraft Version

1.20.1

### Mod Version

BotanyPots-Forge-1.20.1-13.0.25

### Mod Loader

Forge

### What environment are you running the mod in?

All

### Issue Description

Using a time in a bottle ([TIAB](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle-forge) on botany pots does not speed them up at all, even thought the TIAB still works on other block entities/machines. Reporting issue here as its only the botany pots we have experienced this issue with.

**Comment by Darkhax** [comment]
Hello, I tried this out with version `4.0.4-mc1.20.1` of TIAB and it seems to work fine? The main issue I can see is that the renderer flickers which makes sense because the block is skipping render updates.

https://github.com/Darkhax-Minecraft/BotanyPots/assets/2250798/3824ae4a-5c51-460b-8c98-6c096943d689

**Comment by milkev** [comment]
Apologies, i swear it wasnt working when i was testing it before, but its working today and i havent changed anything so... ;-;
