### ISSUE TITLE
[FEEDBACK] <Upgrades for Speed-Silk-Fortune?>

### ISSUE THREAD

**Issue by KhyshaM7** [Darkhax-Minecraft/BotanyPots#389]
### Minecraft Version

1.20.4 and 1.20.1

### Mod Loader

Fabric

### Feedback

Hi, so.. I'm playing with the mod and I just think that would be cool if you can  upgrade your pots with different "skills".

For example a speed boost will cause the item to drop sooner, Silk (Only when the addon Botany Trees is avaliable) would make that the trees drop the leaves and not sticks, a fortune upgrade will make the drops double.. The pot could have only 2 or 1 slot to apply the upgrade, so you need to think what you want.

The upgrade could be applied at a smithing table or just inside the pot.. with a way to take it off.

**Comment by Darkhax** [comment]
Hello, thank you for your feedback. Players can already increase the growth speed by using different soils and in the future soils will be able to change drops so this alternative system would convolute the overall design. The reason trees don't drop leaves is not because the pot lacks silk touch, it's because leaves were intentionally removed from the loot pool in BotanyTrees due to overwhelming player demand. If someone wants to make a datapack to add them pack they could.
