### ISSUE TITLE
[FEEDBACK] Add support for Create: Dreams & Desires

### ISSUE THREAD

**Issue by Bentcheesee** [Darkhax-Minecraft/BotanyPots#406]
### Minecraft Version

1.18.2

### Mod Loader

Forge

### Feedback

Add in support for Rubber Trees for Create: Dreams & Desires

Possible loot table:
```
{
    "bookshelf:load_conditions":[{
            "type":"bookshelf:item_exists",
            "values":["create_dd:rubber_sapling"]
        }],
    "type":"botanypots:crop",
    "seed":{"item":"create_dd:rubber_sapling"},
    "categories":["dirt"],
    "growthTicks":2400,
    "display":{"block":"create_dd:rubber_sapling"},
    "drops":[
        {
            "chance":1.00,
            "output":{"item":"create_dd:rubber_log"},
            "minRolls":2,
            "maxRolls":4
        },
        {
            "chance":0.10,
            "output":{"item":"minecraft:stick"},
            "minRolls":1,
            "maxRolls":2
        },
        {
            "chance":0.15,
            "output":{"item":"create_dd:rubber_sapling"}
        },
        {
            "chance":0.05,
            "output":{"item":"create_dd:crystallized_sap"}
        }
    ]
}
```

**Comment by Darkhax** [comment]
The BotanyTrees add-on has been updated to add support. I didn't include the crystallized sap because it does not appear to drop from the log or leaves when broken under normal circumstances. I checked their loot tables and tried breaking the blocks in game with my hand, an axe, and letting the leaves despawn. If I missed something and they do drop the sap without a special tool please let me know and I will update this. 

- MC 1.18.2 -> 4.0.15
- MC 1.20.1 -> 9.0.15

**Comment by Bentcheesee** [comment]
I put the crystalized sap in there as a small little shortcut.  How you obtain Crystalized Sap in C:DD is by Draining various logs and then using a Mechanical Mixer to mix 500 (number may be incorrect) mB of Sap to 1 Crystalized Sap.  As BotanyPots/Trees cannot create liquids as an output, 1 Crystalized sap with a very small drop chance sounded appropriate to me as one still gets the logs and things anyways
