### ISSUE TITLE
[BUG] Thousands of Render Errors on the server

### ISSUE THREAD

**Issue by SkyKingPX** [Darkhax-Minecraft/BotanyPots#411]
### Minecraft Version

Forge 1.20.1-47.3.1

### Mod Version

13.0.36

### Mod Loader

Forge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

The server starts normally but there are thousands of these errors:
[09:55:36] [main/WARN] [Radium Class Analysis/]: Radium Class Analysis Error: Class net.darkhax.botanypots.block.BlockBotanyPot cannot be analysed, because getting declared methods crashes with RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER.

![grafik](https://github.com/user-attachments/assets/03001552-8097-4dd1-ab17-bc5b165c0609)

**Comment by Darkhax** [comment]
Hello, thanks for taking the time to report this issue. This issue is caused by the Radium mod. Unfortunately the developers of Radium insist that this is everyone elses problem and refuse to fix this. I've heard from many other players that Canary does not have these issues so that may be worth checking out as an alternative. 

To explain the issue in more depth, Botany Pots does not load client side code on the server like Radium claims. This issue is specifically caused by Radium attempting to analyze modded code in an unsafe way. They have intentionally chosen to spam you with this message rather than handling the issue appropriately. Their proposed solution of using `@OnlyIn` goes against the best practices for developing Forge mods and multiple developers from the Forge team have advised against doing that.

**Comment by SkyKingPX** [comment]
Thank you for the detailed answer.
I will swap these mods out in my new release :)
