### ISSUE TITLE
Support item pipes?

### ISSUE THREAD

**Issue by Jaeiya** [Darkhax-Minecraft/BotanyPots#57]
I was going to have the hopper pots drop their contents into Mekanism logistic pipes, but they don't connect. This might be because the pots are not considered inventory and therefore can't be interacted with that way. I was wondering if that could be a future feature if it's not too much effort?

**Comment by papaworld** [comment]
Tubes Reloaded works great with botany pots and bonsai trees... the pipe looks like it is not connected, but, indeed it works.

Mechanism Transport Pipes do not work with botany or bonsai... although, Meka Transport Pipe will eject to Tubes Reloaded Pipe... but not the other way around. Hope this helps ya, enjoy!

**Comment by Jaeiya** [comment]
Thanks for the workaround 😄

**Comment by Darkhax** [comment]
Yeah, the issue here is that the botany pot is not an inventory block so the pipe can not connect to it. Bottany pots don't have a buffer and will push to the connected inventory. Funny enough this means that the pipes which don't work are not inventories either as the pot could push into them otherwise lol.

**Comment by Darkhax** [comment]
I've updated the pot to allow visual connections to most pipes. The Mekanism pipes specifically do not allow other blocks to put items into them though, they can only pull items out. The Botany Pot has no internal inventory or buffer so they are logically incompatible. Mekanism has similar issues with other mods and even several vanilla blocks.
