### ISSUE TITLE
[1.15/1.16][suggestion|question] Mystical Agriculture support.

### ISSUE THREAD

**Issue by Bass2style** [Darkhax-Minecraft/BotanyPots#71]
Hi,

i discovered your mod few days ago, mainly because i whas searching an alternative to the Garden Cloches, that doesn't support Mystical (for the moment) on his 1.15+ version.
i saw that a great number of the Mystical seeds are supported, but some base seeds aren't, and custom seeds are not compatible anyway.
do you think it's possible to bypass this limitation to "not requiring crux" seeds ? something like "uh, i found a Mystical seed, ok, it's working", without the need to update the mod everytime you have new seeds or something.

i'm not a dev, only an user that test, use mods and report bugs and suggest things, so, i dont really know the limitations of my question, but, do you think it's possible to do ?

thanks for your attention, have a nice day.

**Comment by Darkhax** [comment]
The main reason some myst agr seeds are not supported here is because the mod does not know about them. A lot of their seeds get unlocked when you install other mods so my mod doesn't have any data files. When a seed if found the data file can be contributed to this mod and it will work. A lot of the new seeds submitted by the community are only defined for 1.16+.

This mod is data driven meaning you can easily add new crops for anything you want, including making your own new crops. This can be done using data pack files which mods, modpacks, and servers can define. You can learn more here: https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information

While it is possible to auto-detect all the seeds, it is bad practice to mix auto-generated data with user configs.
